FROM registry.fly.io/tagium-cobalt@sha256:ed27935513f69bb6ed754daa7296a14dff85490f6c9623f11e197e40106101a0

COPY --chown=node:node cobalt-machine-proxy.mjs /app/cobalt-machine-proxy.mjs
COPY --chown=node:node cobalt-soundcloud.mjs /app/src/processing/services/soundcloud.js
COPY --chown=node:node cobalt-soundcloud-helpers.mjs /app/cobalt-soundcloud-helpers.mjs

CMD ["node", "/app/cobalt-machine-proxy.mjs"]
